const ROLE = {
  ADMIN: 'ROLE_SYSTEM_ADMIN',
  CLIENT: 'ROLE_CLIENT',
  SERVICE_PROVIDER: 'ROLE_SERVICE_PROVIDER',
  BUSINESS_EMPLOYEE: 'ROLE_BUSINESS_EMPLOYEE',
  MEMBER: 'ROLE_MEMBER',
  ACCOUNTANT: 'ROLE_ACCOUNTANT',
  HEALTH_MODERATOR: 'ROLE_HEALTH_MODERATOR',
  MEDICAL_APPRAISER: 'ROLE_MEDICAL_APPRAISER',
  BUSINESS_APPRAISER: 'ROLE_BUSINESS_APPRAISER',
};

export default ROLE;
